name: CI ReUse Dev
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
jobs:
  Nodejs_Build:
    if: input.appType == 'nodejs'
    runs-on: self-hosted
    steps:
      - run: echo OK


